name: Docker Image Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-push-scan:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Backend Image
        run: docker build -t $DOCKER_USERNAME/backend:latest ./backend

      - name: Build Frontend Image
        run: docker build -t $DOCKER_USERNAME/frontend:latest ./frontend

      - name: Push Backend Image
        run: docker push $DOCKER_USERNAME/backend:latest

      - name: Push Frontend Image
        run: docker push $DOCKER_USERNAME/frontend:latest

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.DOCKER_USERNAME }}/backend:latest"
          format: "table"
          output: "backend-trivy-report.txt"

      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "${{ env.DOCKER_USERNAME }}/frontend:latest"
          format: "table"
          output: "frontend-trivy-report.txt"

      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            backend-trivy-report.txt
            frontend-trivy-report.txt